FROM boky/postfix:latest

RUN apt-get update \
  && apt-get install -y --no-install-recommends postgresql-client netcat-openbsd \
  && rm -rf /var/lib/apt/lists/*

COPY scripts/entrypoint-postfix.sh /entrypoint-postfix.sh
COPY postfix-config/ /etc/postfix/

RUN chmod +x /entrypoint-postfix.sh

ENTRYPOINT ["/entrypoint-postfix.sh"]
CMD ["postfix", "start-fg"]
